### ISSUE TITLE
Multiline selection jumps

### ISSUE THREAD

**Issue by tambaqui** [pdf2htmlEX/pdf2htmlEX#103]
This is just a duplicate of this [issue](https://github.com/coolwanglu/pdf2htmlEX/issues/62) from the original pdf2htmlEX repository.

Selection "jumps" to top of page when selecting multiple paragraphs. And when line spacing between lines is more, selecting is worst.

I did some testing and found a workaround that works relatively well for some cases with simple texts. It would basically consist of using the `::before` pseudoclass for `.t` class in a way that "extends" the line beyond its actual height.

```css
.t:before {
  content: '';
  display: inline-block;
  position: absolute;
  height: 1000%;
  width: 100%;
  z-index: -1;
}
```

The 1000% height is exaggerated to cover a wide range of variable line spacing. The problem with this solution is that it requires the text to follow the same rendering order as the order it occupies in the DOM, since if there are absolutely positioned blocks that do not follow the order of the DOM, and they are rendered above preceding blocks in the DOM, they could block the selection in the other blocks. It is also not appropriate if there are rotated parts of text in the document for the same reason.

I would appreciate some other better solution for this problem.
